src/lib/electron.ts
src/lib/store.ts

Fixes #10 
Should the context get cleared too?

feat: Add option to clear breadcrumbs from previous sessions

---

src/lib/electron.ts

feat: Normalise paths

---

package.json
src/lib/electron.ts
src/lib/store.ts

fix: Remove electron peerDependency

---

package.json
test/e2e/index.test.ts
test/e2e/test-context.ts
test/unit/url-normalize.test.ts

- Lint and prettier on tests too
- Cover the 4 basic crash types

Add more tests

---

.github/release.yml
.travis.yml
CHANGELOG.md

After this, we just have to push a new tag and the release will happen automatically.

ci: Configure Zeus and bot releases

---

src/lib/backend.ts
test/e2e/context.ts
test/e2e/index.test.ts
test/e2e/test-app/fixtures/javascript-unhandledrejection.js
test/e2e/test-app/fixtures/sentry-basic.js
test/e2e/test-app/fixtures/sentry-onfatal-exit.js
test/e2e/test-app/index.html
test/e2e/test-app/load-sentry.js
test/e2e/test-app/main.js

Fixes #45 
Also added a renderer `unhandledrejection` test

Fix: onFatalError

---

README.md
example/sentry.js
package.json
src/index.ts
src/sdk.ts
test/e2e/test-app/fixtures/sentry-basic.js
test/e2e/test-app/fixtures/sentry-onfatal-exit.js
yarn.lock

Changes required by https://github.com/getsentry/raven-js/pull/1292

ref: Rename Sentry.create to Sentry.init in all layers

---

src/index.ts
src/uploader.ts

fix: Correctly shim promisify for Electron <1.8

---

docs/native.rst
src/backend.ts

fix: Disable native handler for MAS builds

---

package.json
yarn.lock

fix: Lock dep versions

---

package.json
src/dispatch.ts
src/index.ts
src/main/backend.ts
src/main/client.ts
src/main/integrations/electron.ts
src/main/integrations/onuncaughtexception.ts
src/main/integrations/sdkinformation.ts
src/main/transports/net.ts
src/main/uploader.ts
src/renderer/backend.ts
src/renderer/client.ts
src/sdk.ts
yarn.lock

This requires https://github.com/getsentry/sentry-javascript/pull/1512
and a new release of all packages.
Fixes #109
Fixes #106
Fixes #94

feat: Update code to reflect changes in core

---

package.json
src/common.ts
src/dispatch.ts
src/main/client.ts
src/main/index.ts
src/renderer/client.ts
test/e2e/index.test.ts
yarn.lock

Fixes #101
```
const { init, getCurrentFrontend } = require('@sentry/electron');
init({
dsn: 'DSN',
beforeSend: event => {
getCurrentFrontend().showReportDialog();
return event;
},
});
```
docs: https://github.com/getsentry/sentry-docs/pull/389

feat: Expose showReportDialog

---

CHANGELOG.md
example/sentry.js
package.json
src/main/client.ts
src/renderer/client.ts
test/e2e/index.test.ts
test/e2e/utils.ts
yarn.lock

- Additional failing test that demonstrates broken persisted scope

fix: Scope not persisted

---

src/main/normalize.ts

Fix the event_id: '[undefined]' bug

---

src/common.ts
src/main/backend.ts
src/main/context.ts
src/renderer/backend.ts

Closes https://github.com/getsentry/sentry-electron/issues/193

feat: Support electron 7

---

src/main/normalize.ts

fix: Add try/catch for decode

---

src/renderer/backend.ts

Fix: IPC objects valid for structured clone algorithm

---

.github/ISSUE_TEMPLATE/bug_report.md

change SKD to SDK

---

test/e2e/index.test.ts

Electron 9 should be tested now it's stable.  Also updates the version of Electron 8 being tested by a bit

test: add Electron 9 to E2E

---

example/sentry.js
package.json
src/common.ts
src/dispatch.ts
src/main/backend.ts
src/main/transports/net.ts
yarn.lock

This PR makes it possible to use the crashpad uploader for sending minidumps.
Also bumps `@sentry/*` to the latest version.

[feat]: crashpadUploader

---

package.json
src/main/backend.ts
src/main/uploader.ts
src/main/utils.ts
yarn.lock

Fixes https://github.com/getsentry/sentry-electron/issues/246
Adds electron context with crash reason

feat: render-process-gone

---

example/sentry.js
src/main/transports/net.ts

Fixes https://github.com/getsentry/sentry-electron/issues/250

fix: Rate limit status check

---

.gitignore
CHANGELOG.md
example/Vagrantfile
example/app/index.html
example/app/style.css
example/main.js
example/package.json
example/renderer.js
example/sentry.js
example/webpack.config.js
example/yarn.lock
src/main/backend.ts
src/main/context.ts

feat: Minidump Uploader

---

src/main/transports/net.ts
test/e2e/index.test.ts
test/e2e/preload-app/main.js

feat: Compress uploads

---

CHANGELOG.md
package.json
src/main/uploader.ts
test/e2e/index.test.ts
test/e2e/server.ts

Fix: Correctly handle Breakpad multipart dump format

---

CHANGELOG.md
src/main/ipc.ts

Issue reported [here](https://github.com/getsentry/sentry-electron/issues/370#issuecomment-980492431).

Fix: Enable CORS for custom protocol

---

.github/workflows/new-versions-pr.yml

The new PR creation workflow failed to run because I messed up the yaml 🤦‍♂️

Fix: New PR workflow yaml

---

.github/workflows/new-versions-pr.yml

We obviously need to install before running scripts.

fix: New version PR creation 

---

scripts/build-preload.js

[This comment](https://github.com/getsentry/sentry-electron/issues/370#issuecomment-985536459) reports that the preload build being broken. The build was broken due to a rename which stopped the string replace bundling from working.
This PR fixes the text replacing and adds a check to ensure that the compiled code does not import anything other than Electron.

Fix: preload build 

---

CHANGELOG.md
MIGRATION.md

Prep for stable release:
- Update CHANGELOG
- Add MIGRATION

chore: Update changelog and migration

---

src/renderer/integrations/event-to-main.ts
src/renderer/integrations/scope-to-main.ts
src/renderer/ipc.ts
src/renderer/sdk.ts
test/e2e/test-apps/other/error-entry-point/src/main/index.js

fix: Lazily initialise IPC in renderer

---

CHANGELOG.md
package.json
src/common/index.ts
src/common/walk.ts
src/renderer/integrations/event-to-main.ts
src/renderer/integrations/scope-to-main.ts
test/e2e/test-apps/other/net-breadcrumbs-tracing/package.json
test/e2e/test-apps/other/net-breadcrumbs-tracing/src/main.js
yarn.lock

This also migrates from `walk` to `normalize` so I'm going to tentatively say that #263 is fixed...

Update to latest Sentry SDKs

---

README.md

docs: Remove old links from readme

---

CHANGELOG.md

Fixes some minor formatting issues and adds a PII warning to changelog

Minor improvements to changelog

---

package.json
test/e2e/test-apps/javascript/main-error/event.json
test/e2e/test-apps/other/browser-tracing/package.json
test/e2e/test-apps/other/custom-tracing/package.json
test/e2e/test-apps/other/net-breadcrumbs-tracing/package.json
test/e2e/test-apps/other/net-breadcrumbs/package.json
yarn.lock

Update to Sentry JavaScript 7.8.1

---

CHANGELOG.md

I've copied everything from `4.0.0-beta.1` too as this could be easy to miss.

Update changelog for v4 release

---

src/main/ipc.ts
src/renderer/integrations/scope-to-main.ts
test/e2e/test-apps/other/scope-breadcrumbs/event.json
test/e2e/test-apps/other/scope-breadcrumbs/src/index.html

Attachments added to the renderer process scope we not getting added to the main process scope.

Pass attachment scope changes in renderer processes to main process

---

src/main/integrations/electron-minidump.ts
src/main/integrations/main-process-session.ts
src/main/integrations/sentry-minidump/index.ts
src/main/sessions.ts
src/main/store.ts
src/main/transports/queue.ts

Reverts getsentry/sentry-electron#542
This resulted in data races for file read/write

Revert "feat: Make the store completely async"

---

test/unit/normalize.test.ts
test/unit/stack-parse.test.ts

Ensure that localhost/http URL's are not modified by our stack parse/normalisation code

test: Test localhost URLs are not modified and stack traces are correctly parsed

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/new-electron-versions-pr.yml
.github/workflows/new-sdk-versions-pr.yml
.github/workflows/release.yml

- Update `actions/checkout` version to fix node v12 warnings
- Fix indentation 
- Remove redundant cache

CI: A few CI updates and fixes

---

CHANGELOG.md

Also includes the open #644 so it makes it into a release

chore: Update changelog for fresh 4.3.0 release

---

src/main/ipc.ts

fix: IPC protocol should be registered as secure

---

package.json
src/main/context.ts
src/main/store.ts
src/main/transports/electron-offline-net.ts
src/renderer/sdk.ts
yarn.lock

There were a few `no-return-await` lints to fix!

feat: Update to v7.57.0 of Sentry JavaScript SDKs

---

package.json
src/common/mutex.ts
src/integrations.ts
src/main/integrations/additional-context.ts
src/main/integrations/child-process.ts
src/main/integrations/electron-breadcrumbs.ts
src/main/integrations/electron-minidump.ts
src/main/integrations/main-context.ts
src/main/integrations/main-process-session.ts
src/main/integrations/net-breadcrumbs.ts
src/main/integrations/onuncaughtexception.ts
src/main/integrations/preload-injection.ts
src/main/integrations/screenshots.ts
src/main/integrations/sentry-minidump/index.ts
src/main/store.ts
src/main/transports/queue.ts
src/renderer/integrations/event-to-main.ts
src/renderer/integrations/scope-to-main.ts
src/renderer/sdk.ts
yarn.lock

The code changes are due to the addition of the `Avoid class field initializers` lint.

feat: Update to v7.63.0 of the JavaScript SDKs

---

test/e2e/test-apps/sessions/abnormal-exit-electron-uploader/src/main.js
test/e2e/test-apps/sessions/abnormal-exit/src/main.js
test/e2e/test-apps/sessions/native-crash-main/src/main.js
test/e2e/test-apps/sessions/window-bad/src/main.js

This PR extends the runtime of more session tests to improve e2e test reliability

test: Extend more test times

---

src/index.ts
src/main/index.ts
src/renderer/index.ts

Ass these were added to the base SDKs, they were not added to the exports!

fix: Add missing exports

---

CHANGELOG.md

Updates the changelog for the 4.17.0 release.

meta: Changelog for 4.17.0 release

---

src/common/normalize.ts
src/main/ipc.ts
test/e2e/server/index.ts
test/e2e/test-apps/other/feedback/event.json
test/e2e/test-apps/other/feedback/package.json
test/e2e/test-apps/other/feedback/recipe.yml
test/e2e/test-apps/other/feedback/src/index.html
test/e2e/test-apps/other/feedback/src/main.js

Closes #834
This PR ensures that feedback can be sent from the renderer process and adds a test to ensure the envelopes correctly get passed through the main process.

feat: Support and test `Sentry.sendFeedback`

---

src/main/ipc.ts
test/e2e/test-apps/other/event-listener/package.json
test/e2e/test-apps/other/event-listener/recipe.yml
test/e2e/test-apps/other/event-listener/src/index.html
test/e2e/test-apps/other/event-listener/src/main.js

fix: Duplicate event hookup

---

src/main/integrations/anr.ts

fix: Stop Anr worker when app suspends

---

package.json
src/renderer/sdk.ts
yarn.lock

feat: Update Sentry SDKs to v7.109.0

---

package.json
src/index.ts
src/main/index.ts
src/renderer/index.ts
src/renderer/sdk.ts
yarn.lock

Update v4 branch to use latest SDKs.

feat: Update Sentry SKDs to v7.110.0

---

src/main/normalize.ts
test/e2e/test-apps/other/browser-replay/event-replay.json
test/e2e/test-apps/other/browser-replay/src/index.html

fix: Missing replay scope

---

src/common/normalize.ts
test/e2e/test-apps/other/browser-replay/event-replay.json
test/e2e/test-apps/other/browser-replay/src/index.html

fix: Missing replay scope (v4)

---

package.json
src/renderer/sdk.ts
yarn.lock

Update to v7.112.0 of the JavaScript SDKs

feat: Update to v7.112.0 of the JavaScript SDKs

---

MIGRATION.md
README.md

Updates the Readme and adds a v4 to v5 section to the Migration docs.

docs: Migration & Readme

---

CHANGELOG.md

I also had to copy the latest v4 releases from that branch.

meta: Changelog for 5.0.0-beta.0 release

---

test/e2e/index.test.ts

Fixing CI issues that are only hit when releasing.

build: Skip example app tests when required

---

src/main/integrations/net-breadcrumbs.ts
test/e2e/test-apps/other/net-breadcrumbs-tracing/event.json

feat: Include trace origin in auto spans

---

README.md

ref https://github.com/getsentry/team-sdks/issues/87

chore: Add contribution image to electron sdk readme

---

package.json
src/main/index.ts
src/main/integrations/electron-minidump.ts
src/main/transports/electron-net.ts
src/renderer/index.ts
src/renderer/sdk.ts
yarn.lock

Update JavaScript SDKs to v8.12.0

feat: Update JavaScript SDKs to v8.12.0

---

src/main/transports/electron-net.ts

fix: Pass through status code in transport response

---

src/common/scope.ts

Closes #1022 
To PR reviewers... am I merging the scopes with the correct hierarchy?

fix: Sync global scope to main process

---

CHANGELOG.md

chore: Changelog for v5.8.0 release

---

src/main/integrations/anr.ts

fix: Disable ANR when screen locked

---

package.json
src/renderer/sdk.ts
yarn.lock

- Closes #876
- Should also fix this but needs tests #1011

feat: Update JavaScript SDKs to v8.46.0

---

src/main/integrations/electron-context.ts
test/e2e/test-apps/javascript/main-error/event.json
test/e2e/test-apps/javascript/main-error/src/main.js

- Ref https://github.com/getsentry/team-sdks/issues/118

feat: Explicitly set `user.ip_address: {{auto}}`

---

src/main/integrations/net-breadcrumbs.ts
test/e2e/test-apps/other/net-breadcrumbs/event.json

- Ref https://github.com/getsentry/team-sdks/issues/100

feat: Set log level for `net` breadcrumbs based on status code

---

package.json
src/renderer/sdk.ts
yarn.lock

Updatea JavaScript SDKs to v9.6.0

feat: Update JavaScript SDKs to v9.6.0

---

src/main/ipc.ts
test/e2e/server/index.ts
test/e2e/test-apps/other/browser-tracing/event.json

fix: Missing DSC envelope header for renderer tracing (v5)

---

CHANGELOG.md
package.json
src/main/index.ts
src/renderer/index.ts
src/renderer/sdk.ts
src/utility/index.ts
yarn.lock

Also updates the changelog for release

feat: Update JavaScript SDKs to v8.55.0

---

.github/workflows/release-comment-issues.yml

Add the CI workflow from the JavaScript repo

ci: Notify issues for releases

---

.github/workflows/codeql-analysis.yml

CodeQL is failing to run in some PRs.
I'm adjusting the CodeQL configuration here to their updated actions and steps (ie. `javascript` --> `javascript-typescript`). I'm also removing the "autobuild" step as it is unnecessary for JS/TS.

codeql: update configuration

---

package.json
src/main/index.ts
src/main/integrations/electron-minidump.ts
src/main/integrations/net-breadcrumbs.ts
src/main/integrations/preload-injection.ts
src/main/integrations/renderer-anr.ts
src/main/integrations/screenshots.ts
src/main/integrations/sentry-minidump/index.ts
src/main/integrations/sentry-minidump/minidump-loader.ts
src/main/ipc.ts
src/main/sdk.ts
src/main/sessions.ts
src/main/stack-parse.ts
src/main/store.ts
src/main/transports/offline-store.ts
src/main/utility-processes.ts
src/renderer/index.ts
src/renderer/ipc.ts
src/renderer/sdk.ts
src/utility/index.ts
src/utility/sdk.ts
yarn.lock

All of the changes are due to `logger` being renamed to `debug`.

feat: Update JavaScript SDKs to v9.40.0

---

src/main/integrations/child-process.ts
src/main/integrations/electron-breadcrumbs.ts
src/main/integrations/net-breadcrumbs.ts
test/e2e/test-apps/other/child-process/test.ts
test/e2e/test-apps/other/renderer-error/src/index.html
test/e2e/test-apps/other/renderer-error/test.ts

feat: Capture logs for Electron integrations

---

.npmignore

fix: Ensure `native` directory ends up in package

---

src/main/index.ts
src/renderer/index.ts
src/utility/index.ts

fix: Export `ErrorEvent` type
