getsentry/sentry-electron

src/lib/electron.ts
Fixes #13 and also tracks multiple renderer processes.
`extra.crashed_process` = `browser` | `renderer[${webContents.id}]`
=> feat: Identify process in JavaScript and native crashes

package.json
Just so no one else gets hideous `Error: Cannot find module '..'` error anymore.
=> build: Run build as preexample step

.travis.yml, example/main.js, package.json, src/lib/electron.ts, test/e2e/index.test.ts, test/e2e/spectron-helper.ts, test/tslint.json, test/unit/url-normalize.test.ts, test/url-normalize.test.ts, yarn.lock
Changes
- Split tests into `unit` and `e2e`
- Run unit tests in `electron-mocha` and e2e in `mocha`
- Use `ts-node/register` so TypeScript tests don't require pre-compilation step
- Simplify `normalizeUrl` and add some initial tests (Fixes #21)
=> fix: Many improvements

src/lib/electron.ts
This exposes `onFatalError` in the electron options.
With that you should be able to overwrite the default behaviour of 
```
console.error(err && err.stack ? err.stack : err);
global.process.exit(1);
```
=> feat: Add option for onFatalError

test/e2e/context.ts, test/e2e/index.test.ts, test/e2e/preload-app/index.html, test/e2e/preload-app/main.js, test/e2e/preload-app/package.json
Adds a test which tests a renderer with `nodeIntegration` disabled and `SentryClient` created via preload script
=> feat: Add nodeIntegration disabled test

README.md, example/sentry.js, package-lock.json, package.json, src/backend.ts, src/frontend.ts, src/index.ts, src/normalize.ts, src/sdk.ts, src/uploader.ts, test/e2e/context.ts, test/e2e/index.test.ts, test/e2e/server.ts, test/e2e/test-app/fixtures/native-main.js, test/e2e/test-app/fixtures/native-renderer.js, test/e2e/test-app/fixtures/sentry-basic.js, test/e2e/test-app/fixtures/sentry-onfatal-exit.js, test/e2e/utils.ts, test/tslint.json, yarn.lock
For now, in order for this to work, I recommend checking out the latest commit of 
https://github.com/getsentry/raven-js/tree/4.0.0-wip locally and run 
`yarn link` in every sub package.
Also, don't forget to run `yarn build` in raven-js to have the latest builds transpiled.
Then run this in `sentry-electron``yarn link @sentry/core @sentry/browser @sentry/node @sentry/utils @sentry/typescript @sentry/shim`
Then everything should work, the new style of calling things for users goes through the shim.
Shim > Frontend > Backend
=> ref: Update to latest core

src/backend.ts
The default for `maxBreadcrumbs` was incorrectly set to `100`. However, documentation says `30`, with a maximum possible value of `100`. This PR fixes this and adds an additional check for negative numbers.
=> fix: Limit maxBreadcrumbs to [0;100] and default to 30

docs/sourcemaps.rst
There is no such function to call.
=> doc: Fix invalid mention of `.install()`

docs/index.rst
This should clarify https://github.com/getsentry/sentry-electron/issues/54, https://github.com/getsentry/sentry-electron/issues/58 and https://github.com/getsentry/sentry/issues/7804
=> doc: Add a disclaimer for on-premise

example/package.json, package.json, src/backend.ts, src/context.ts, src/frontend.ts, src/normalize.ts, src/utils.ts, yarn.lock
The operating system version is still wrong and I think we can do a better job in getting the operating system name (e.g. via user agent). 
Fixes #37
Fixes #40
=> feat: Add context data to events

src/main/context.ts, tsconfig.build.json
The linux distributions need to be checked in a certain order, obviously.
=> fix: Check linux distribution files in correct order

CHANGELOG.md, docs/javascript.rst, src/main/integrations/onuncaughtexception.ts, test/e2e/index.test.ts, test/e2e/test-app/fixtures/sentry-basic.js, test/e2e/test-app/fixtures/sentry-onfatal-exit.js
We decided that we don't want to change the default behaviour that electron has.
Arguing if it's right or not to exit the app by default, we don't want people to experience that the app suddenly exits just after integrating Sentry.
That's why the default behaviour is now:
-> onUncaughtError
-> Send to Sentry
-> if `onFatalError` is set, call `onFatalError(error)`
-> else show electron dialog
If the user wants his app to crash he has to set `onFatalError` and call `process.exit` in there see file changes of this PR.
=> feat: Don't process exit on oncaught error

README.md
The README Deep Dive section URLs are all 404 now. This PR fixes those links to point to the new URLs.
=> Fixed Deep Dive URLs to point to the new locations

src/main/backend.ts, src/main/client.ts, src/main/integrations/electron.ts, test/e2e/index.test.ts
- Moves event normalisation out from the Electron integration
- Moves instrumented electron breadcrumbs into the Electron integration
This way, if a user sets `defaultIntegrations: false`, path normalisation will still work but the Electron breadcrumbs will no longer be written.
=> Fix: Change Electron integration functionality 

src/main/client.ts, test/e2e/index.test.ts, test/e2e/test-app/fixtures/sentry-custom-release.js
`super.prepareEvent` should be called before normalising the event.
Added tests to check this for both JavaScript and native.
=> fix: Custom release string not sent with minidump

src/main/context.ts
Fixes #130 
I'm guessing this worked at some point because `toString()` was converting the returned object into something that worked with the regex. 
Here is what `execFile` returns:
=> fix: macOS info

src/main/context.ts
This is the proposed alternative solution of PR #134 
Looking though the code it looks like the `require()` call in `getPackageJson` is the only one that needs the `module.require` hack to be introduced for. If there are any that I missed, please let me know!
Ref: webpack/webpack#7728
Closes: getsentry/sentry-electron#132
=> fix: use module.require in place of require for dynamic includes

src/main/integrations/onuncaughtexception.ts
Fixes #146 
This means if you start using `sentry-electron` and already have `uncaughtException` handler in place, the default Electron dialog will not be displayed.
=> fix: Only show dialog if there is no custom uncaughtException handler

src/main/normalize.ts, test/unit/normalize.test.ts
This PR handles app paths that have parentheses and other RegExp characters.
=> escape base path in normalizeUrl function

src/main/backend.ts, src/main/uploader.ts
It seems that the crashHandler in some versions have troubles uploading native crashes if no `submitUrl` is set. This PR sets something in there so it works as expected.
Strange thing is, that we documented it but didn't set anything 🤔 
https://github.com/getsentry/sentry-electron/pull/164/files#diff-96bd4e745f003940949074e9dc09c1bfR182
=> fix: Native crashes not being uploaded because no submitUrl is set

src/common.ts, src/main/backend.ts, src/main/integrations/electron.ts, test/e2e/index.test.ts, test/e2e/test-app/fixtures/sentry-custom-renderer-name.js
When you have multiple windows `renderer[3]` is not particularly helpful.
Usage:
```typescript
const names = ['main-window', 'file-viewer'];
// or more likely something more complex in your window manager
init({
dsn: `__DSN__`,
getRendererName(contents: Electron.webContents) {
return names[contents.id];
},
});
```
=> Feat: Allow custom naming of rederer processes

src/main/uploader.ts
Ensures that `win-ca` uses the Sentry cache path for writing certificate files. We know for sure this is writable. This should hopefully fix #204.
=> Fix: Fixed location for win-ca write path

package.json, src/main/uploader.ts, test/e2e/index.test.ts, yarn.lock
Reverts to using `electron-fetch` rather than `node-fetch`+`win-ca`.
It appears that all the bugs have been fixed in the latest Electron v7 + v8-beta versions.
=> Fix: Try electron-fetch with latest Electron releases

src/common.ts, src/main/backend.ts, src/main/client.ts, src/main/context.ts, src/main/uploader.ts, src/renderer/backend.ts
cc @koenoe
This allows usage of `sentry-electron` with the `remote` module disabled in renderers:
```
const mainWindow = new BrowserWindow({
webPreferences: {
enableRemoteModule: false
}
})
```
To support this you have to pass the app name to sentry options:
```
const { init } = require('@sentry/electron');
init({
dsn: 'https://343434343434343@sentry.io/5656565',
appName: 'My Great App',
});
```
Add some tests!
=> Feat: Allow usage without remote module

src/common.ts, test/e2e/index.test.ts
Fixes #211 and updates Electron test versions.
I'm also working on some tests to ensure this doesn't regress.
=> Fix: Webpack compile warning

src/main/backend.ts, src/renderer/backend.ts
IPC uses the V8 serializer so I understand why we send it through `JSON.parse(JSON.stringify(` to ensure that no stray functions could break it, it's needless to do that in the renderer and _then_ send it through the serializer as well.  This PR is a small perf tweak to stringify in the renderer and parse in the main process which means the V8 serializer isn't _also_ serializing the object, rather just a string
=> perf: dont double serialize IPC messages

src/main/integrations/electron.ts
Hey, I am running to an error caused by an attempt to access a destroyed web contents. According to the error logged to Sentry, it originates from this line of code. See:
First of all, we have snippet of code intended as a security measure recommended by electron documentation. See:
https://electronjs.org/docs/tutorial/security#13-disable-or-limit-creation-of-new-windows
```ts
app.on('web-contents-created', (event, webContents) => {
webContents.on('new-window', (event) => {
event.preventDefault();
// do global custom behavior if needed.
});
});
```
The electron integrations is hooking into the same `web-contents-created` to collect breadcrumbs on the web contents. However, due to the use of `setImmediate`, there will be a race condition between when the `webContents` gets destroyed and …
=> Fix: Check for webContents.isDestroyed before hooking for breadcrumbs

package.json, src/main/backend.ts, src/main/integrations/electron.ts, src/main/transports/net.ts, yarn.lock
Basically a no-op change but at least it's actually API now, no need for the `any` cast.
At some point we should look at version detection to support the new API --> https://www.electronjs.org/docs/breaking-changes#deprecated-crashreportergetcrashesdirectory
=> fix: getCrashesDirectory is documented as API now

.github/workflows/build.yml, example/package.json, src/main/integrations/onuncaughtexception.ts
This fixes a weird bug where we capture an exception which isn't detected as an error and therefore be captured as `Non-Error exception captured with keys: message, name, stack`
=> fix: Create error object in case we cant detect it

src/main/uploader.ts
The minidump attachment is missing a `filename` header which causes it to get
dropped in Sentry. While this is bug across Relay and Sentry, the filename of
attachments should always be added to item headers.
See https://github.com/getsentry/develop/pull/140
=> fix(minidump): Add filenames to attachment items

src/main/uploader.ts
The initial version of the Electron SDK used to send minidumps to an endpoint without the trailing slash since the server initially did not support this by mistake. This has long been fixed, and the current version of the SDK even requires the Envelope endpoint for most of its operation.
Both in the [endpoint docs](https://docs.sentry.io/platforms/native/guides/minidumps/#minidump-integration) and [Relay's operating guidelines](https://docs.sentry.io/product/relay/operating-guidelines/#request-routing), we only document the URL with a trailing slash.
=> fix(uploader): Add slash to minidump upload URL

src/renderer/backend.ts
This disables the starting of the crash handler in the renderer process. This is necessary for it to work on Electron 12.
This still needs validation.
Fixes #229
=> feat: Do not start crash reporter in renderer

src/electron-version.ts, src/main/backend.ts, src/main/uploader.ts, src/renderer/backend.ts, test/e2e/index.test.ts
The codebase has numerous ways to feature-check Electron versions as APIs are changed or deprecated.
These changes:
- Move all Electron version parsing and checks to a single file
- Bump the e2e test versions
- Skips v3 and v4 from e2e tests on Windows. My local tests seem to suggest these versions don't close and stay open consuming cpu
=> Fix: Unify Electron version checks

package.json, src/main/backend.ts, test/e2e/index.test.ts, test/e2e/multi-part.ts, test/e2e/server.ts, test/e2e/test-app/fixtures/scope-data-merged.js, yarn.lock
- Bump all dependencies in `yarn.lock` so dependabot can ~~have a break~~ take a hike.
- Only apply scope in main process if the object from the renderer has properties
- Add a test for this
This doesn't fully fix underlying issues with merging scope from multiple processes but negates the most common/nasty where empty renderer scope clears out all main scope. The issue of correctly merging scope from multiple processes needs revisiting.
=> Fix: Dont clobber scope in main process when renderer passes empty scope

src/common.ts
If require is undefined the following code checking for the existence of require will throw a reference error so the nicer custom error message is never displayed to the user.
=> Check for require with typeof

src/renderer/backend.ts, test/e2e/index.test.ts, test/e2e/isolated-app/src/renderer.js, yarn.lock
Fixes #316
- Call `_setupScopeListener` from all renderer contexts
- Update isolated test to check user scope is passed from isolated context
- Also limit walk depth to negate #263
=> Fix: Missing scope updates from isolated renderer

src/renderer/backend.ts
Fixes #329 
The event payload had `{ breadcrumbs: undefined, ... }` and when this was passed through `walk` it was getting converted to the string `'[undefined]'` which was passed through IPC. In the the main process this was being interpreted as 11 individual breadcrumbs, each a single character long!
=> Fix: Undefined event breadcrumbs results in spurious breadcrumbs after serialization

CHANGELOG.md, src/main/transports/net.ts
Fixes #344 
I looks like the fix is as simple as handling the `error` event:
https://github.com/electron/electron/issues/24948
=> Fix: Handle response error event

.github/workflows/build.yml, test/e2e/index.test.ts
With e2e tests run in parallel the total run time goes from ~12 minutes to ~8 minutes. 
The limiting factor is the Github Actions limit of 5 concurrent macOS builds. Without this limit, the total time would be more like 6 minutes.
=> test: Run e2e tests in parallel

example/yarn.lock, test/e2e/isolated-app/yarn.lock, test/integration/bundle-test-app/yarn.lock, yarn.lock
=> fix: Dependabot alerts

.eslintrc.js, CHANGELOG.md, src/main/backend.ts, test/e2e/index.test.ts, test/e2e/test-app/fixtures/sentry-electron-uploader-main.js, test/e2e/test-app/fixtures/sentry-electron-uploader-renderer.js
I'm not sure how long it will take to get #361 merged so this PR adds this functionality to v2.
ref @nornagon comment here **https://github.com/getsentry/sentry-electron/pull/340#issuecomment-901318422**
=> Fix: Add `release` and `environment` to electron uploader `initialScope`

CHANGELOG.md, src/renderer/client.ts
This change fixes a race condition over IPC found in the v3 branch where `initialScope` passed to the renderer could cause the initial scope to be lost in the main process.
`initialScope` was added so that we could have user ids in crashes sent via the build in electron uploader. That feature will only work if passed to `init` in the main process so this is a non-breaking change.
=> Fix: Possible race condition with `initialScope` over IPC

CHANGELOG.md, package.json, scripts/update-version.js, src/main/context.ts, src/main/version.ts
Fixes #365 
Some bundler configurations do not automatically load json files. This PR backports a change from the v3 PR where the SDK version is written to a TypeScript file in a `prebuild` script.
=> Improve compatibility with bundlers

examples/electron-forge-webpack/event.json, examples/electron-forge/event.json, examples/webpack-context-isolation/event.json, src/main/context.ts, src/main/electron-normalize.ts, src/main/sdk.ts, src/renderer/integrations/event-to-main.ts, test/e2e/test-apps/javascript/main-error-custom-release/event.json, test/e2e/test-apps/javascript/main-error/event.json, test/e2e/test-apps/javascript/main-unhandledrejection/event.json, test/e2e/test-apps/javascript/renderer-error-custom-env/README.md, test/e2e/test-apps/javascript/renderer-error-custom-env/event.json, test/e2e/test-apps/javascript/renderer-error-custom-env/package.json, test/e2e/test-apps/javascript/renderer-error-custom-env/src/index.html, test/e2e/test-apps/javascript/renderer-error-custom-env/src/main.js, test/e2e/test-apps/javascript/renderer-error-custom-release/event.json, test/e2e/test-apps/javascript/renderer-error/event.json, test/e2e/test-apps/other/browser-tracing/event.json, test/e2e/test-apps/other/custom-renderer-name/event.json, test/e2e/test-apps/other/scope-breadcrumbs/event.json, test/e2e/test-apps/sessions/javascript-error/event.json
I found a few issues where `environment: 'production'` was being added to events by `@sentry/core` and overwriting our defaults.
=> Fix: environment

test/e2e/context.ts, test/helpers.ts, test/unit/persist-queue.test.ts
The units tests do some checks to ensure that files are correctly cleaned up. However, this cleanup occurs asynchronously so we should delay to ensure this has had enough time to complete.
=> Fix: Wait before counting files in unit tests

src/common/index.ts, src/common/process.ts, src/main/index.ts, src/renderer/index.ts, test/e2e/test-apps/other/error-main-in-renderer/package.json, test/e2e/test-apps/other/error-main-in-renderer/recipe.yml, test/e2e/test-apps/other/error-main-in-renderer/src/index.html, test/e2e/test-apps/other/error-main-in-renderer/src/main.js, test/e2e/test-apps/other/error-renderer-in-main/package.json, test/e2e/test-apps/other/error-renderer-in-main/recipe.yml, test/e2e/test-apps/other/error-renderer-in-main/src/index.html, test/e2e/test-apps/other/error-renderer-in-main/src/main.js
We make a best effort to have the correct code bundled automatically for each process via `package.json/exports` but it will not work in all cases. 
This is likely to occur for example when using ES modules in the main process and loading via the root export:
```ts
import * as Sentry from '@sentry/electron';
```
Previously users would see an error with either `windows is not defined` or `Cannot read properties of undefined (reading 'isReady')` which gives users no idea how to fix this.
These changes provide a better developer experience if a bundler loads the incorrect code for an Electron process by displaying a useful message which guides the user to a solution. 
```
Error: This code is intended to run in the Electron renderer process but is currently running in the main process.
This …
```
=> feat: Throw useful errors if code loaded in incorrect process

src/common/types.ts, src/main/electron-normalize.ts, src/main/integrations/child-process.ts, src/main/integrations/net-breadcrumbs.ts
When using version `3.0.0-beta.4` I see some Typescript errors which seem to be because some utility types are not exported.
```
node_modules/@sentry/electron/main/electron-normalize.d.ts:14:41 - error TS2304: Cannot find name 'Optional'.
14 declare type RenderProcessGoneDetails = Optional<Electron.RenderProcessGoneDetails, 'exitCode'>;
~~~~~~~~
node_modules/@sentry/electron/main/electron-normalize.d.ts:19:24 - error TS2304: Cannot find name 'Optional'.
19 declare type Details = Optional<Electron.Details, 'exitCode'>;
~~~~~~~~
node_modules/@sentry/electron/main/integrations/child-process.d.ts:19:35 - error TS2304: Cannot find name 'OrBool'.
19     constructor(options?: Partial<OrBool<ChildProcessOptions>>);
~~~~~~
node_modules/@sentry/electron/main/integrations/net-breadcrumbs.d.ts:26:59 …
```
=> fix: Export utility types

src/index.ts, src/integrations.ts
When initialising with `Sentry.init({...})` make options with default optional in Typescript.
i.e. `ipcMode` and `getSessions`.
See https://github.com/getsentry/sentry-electron/issues/370#issuecomment-1030156807
=> fix: Do not require options with defaults in Typescript

src/main/integrations/child-process.ts, test/e2e/test-apps/other/child-process/src/main.js
While working on the docs, I realised that the options for the `ChildProcess` integration would be more clear if `events` was used instead of `capture`. Better to get this out of the way before releasing a stable release!
So this:
```ts
interface ChildProcessOptions {
breadcrumbs: Readonly<ExitReason[]>;
capture: Readonly<ExitReason[]>;
}
```
Becomes:
```ts
interface ChildProcessOptions {
breadcrumbs: Readonly<ExitReason[]>;
events: Readonly<ExitReason[]>;
}
```
- `breadcrumbs` controls which events generate Sentry breadcrumbs 
- `events` controls which events generate Sentry events.
=> api: Rename `capture` to `events`

CHANGELOG.md, src/common/merge.ts, test/e2e/recipe/normalize.ts, test/e2e/test-apps/other/custom-tracing/event.json, test/e2e/test-apps/other/custom-tracing/package.json, test/e2e/test-apps/other/custom-tracing/recipe.yml, test/e2e/test-apps/other/custom-tracing/src/main.js
Fixes #418
The Electron SDK has a `mergeEvents` function which uses `deepmerge`. This saves having a large manual merge function which has to be kept up to date if any of the event objects change. 
The Sentry tracing `Span` has a custom `toJSON` implementation to convert camelCase properties to snake_case to match the Sentry API guidelines. When the event gets merged with the defaults this function is lost.
This PR:
- Manually copies the spans so their `toJSON` function is still there
- Adds an e2e test to ensure this doesn't break in the future
- Improves the e2e event normalisation code so it doesn't add properties
=> fix: Fix broken serialization of node transaction spans

src/index.ts, src/renderer/index.ts, src/renderer/ipc.ts, test/e2e/context.ts, test/e2e/index.test.ts, test/e2e/test-apps/other/error-entry-point/package.json, test/e2e/test-apps/other/error-entry-point/recipe.yml, test/e2e/test-apps/other/error-entry-point/src/main/index.js, test/e2e/test-apps/other/error-entry-point/vite.config.main.js
Fixes #422 
This PR:
- Wraps `dynamicRequire` so the error message is useful
- Moves `ensureProcess('renderer')` to first usage of `window`
- Adds a test for this
Turns out the existing `ensureProcess` call is completely stripped out because ESM does not support side effects!
=> fix: Improve error messages for incorrectly bundled code

CHANGELOG.md, src/main/transports/electron-net.ts
=> fix: Delete sdk metadata from event before sending

CHANGELOG.md, src/main/ipc.ts
Looks like we were adding a breadcrumbs on every scope change even if there wasn't actually a breadcrumb!
=> fix: Don't add empty breadcrumbs

.github/workflows/new-versions-pr.yml, package.json, yarn.lock
A bug meant not all versions were getting listed correctly.
https://github.com/getsentry/sentry-electron/pull/429/files
=> Fix: Bug when listing latest Electron versions

CHANGELOG.md, src/common/merge.ts, test/e2e/index.test.ts, test/e2e/recipe/parser.ts, test/e2e/server/index.ts, test/e2e/server/multi-part.ts, tsconfig.build.json, tsconfig.esm.json, tsconfig.json
Fixes #431
It looks like we need to use the TypeScript `esModuleInterop` compiler option for `deepmerge`
=> fix: Use `esModuleInterop` for `deepmerge`

CHANGELOG.md, src/main/transports/electron-offline-net.ts
The `setTimeout` function has an interesting implementation detail where, if the delay is bigger than the biggest signed 32-bit integer, it will throw an error and run the callback after 1ms.
The error looks something like this:
```
TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```
Since this error is also reported to Sentry by default, this causes a huge number of errors which can block the main thread.
My workaround for this is to limit the delay to 2,000,000,000 ms so it never overflows.
=> Fix exponential backoff delay overflowing the maximum delay in setTimeout, causing a high number of requests and errors

CHANGELOG.md, src/main/integrations/preload-injection.ts, src/main/ipc.ts, src/main/sdk.ts
A better version of #435
Because we have defaults, in `ElectronMainOptionsInternal`, these properties are not optional so they don't need to checked checked whenever they're accessed.
`ElectronMainOptions` has these properties made optional using some TypeScript trickery: 
```ts
export type ElectronMainOptions = Pick<Partial<ElectronMainOptionsInternal>, 'getSessions' | 'ipcMode'> &
Omit<ElectronMainOptionsInternal, 'getSessions' | 'ipcMode'>;
```
=> Make `getSessions` and `ipcMode` on `ElectronMainOptions` optional

src/main/sdk.ts
Ensures a warning is displayed if main process code is loaded in the renderer.
Fixes #456
=> fix: Throw error if main process code is loaded in renderer

src/main/integrations/main-process-session.ts, src/main/transports/electron-offline-net.ts
This is a partial fix for #454
We should not be throwing for HTTP errors!
=> fix: Don't throw on HTTP errors 

CHANGELOG.md, src/main/integrations/electron-breadcrumbs.ts
Fixes #459
To re-enable:
```ts
init({
dsn: '__DSN__',
integrations: [new ElectronBreadcrumbs({ includeWindowTitles: true })]
})
```
=> fix: Don't capture window titles by default with `ElectronBreadcrumbs` integration

CHANGELOG.md, package.json
=> Fix: export map and sideEffects

CHANGELOG.md, src/index.ts, src/main/index.ts, src/main/integrations/sentry-minidump/index.ts, test/e2e/recipe/index.ts, test/e2e/test-apps/other/close/package.json, test/e2e/test-apps/other/close/recipe.yml, test/e2e/test-apps/other/close/src/index.html, test/e2e/test-apps/other/close/src/main.js
Closes #465 
- Exports `close` and `flush` from `@sentry/node` for the main process
- Exposes `close` and `flush` from the root export and errors if they're called from the renderer
- When `enabled === false`, deletes minidump files rather than sending
- Add a test for the above
=> feat: Allow closing of SDK

src/renderer/sdk.ts
Disable client reports for renderer as the sdk should only send events using the main process.
=> fix: Turn off client reports in renderer process

src/main/integrations/sentry-minidump/index.ts
=> fix: Pass correct event to beforeSend

src/main/integrations/electron-minidump.ts
Fixes https://github.com/getsentry/sentry-electron/issues/507
See: https://github.com/getsentry/sentry-javascript/blob/f372d842ba39d5f107c055e97c5219a05c543dba/packages/core/src/envelope.ts?q=sdkProcessingMetadata#L86
Delete `event.sdkProcessingMetadata` before the event is sent as a minidump to Sentry.
=> fix: Delete sdkProcessingMetadata in minidump pipeline

CHANGELOG.md, package.json, src/renderer/sdk.ts, src/renderer/stack-parse.ts, test/e2e/download.ts, test/unit/stack-parse.test.ts
=> fix: Correctly parse mixed chrome/node renderer stack traces

src/main/transports/electron-offline-net.ts
The Offline transport has an options that allows you to force queueing if the user has not enabled error reporting.
As per [this comment](https://github.com/getsentry/sentry-electron/issues/489#issuecomment-1185027206), I think it would be nice if this function can be async since it's likely to need to do file reads.
=> fix: Allow async `beforeSend` in offline transport

src/main/integrations/preload-injection.ts
Closes #491
It looks like webpack can convert `require.resolve` to relative paths that Electron then complains about. 
This change ensures that we only attempt to use preload paths that came from `require.resolve`, ie. only absolute paths will be attempted.
=> fix: Check preload path is absolute

src/main/integrations/electron-minidump.ts, src/main/integrations/main-process-session.ts, src/main/integrations/sentry-minidump/index.ts, src/main/sessions.ts, src/main/store.ts, src/main/transports/queue.ts
Closes #534
Converts all the store methods to be async and calls async `fs` methods instead of the sync ones.
=> feat: Make the store completely async

package.json, src/main/integrations/additional-context.ts, src/main/sdk.ts, test/e2e/test-apps/other/browser-tracing/package.json, test/e2e/test-apps/other/custom-tracing/package.json, test/e2e/test-apps/other/net-breadcrumbs-tracing/package.json, test/e2e/test-apps/other/net-breadcrumbs/package.json, yarn.lock
This also disables the node `Context` integration since this clashes with existing features in the Electron SDK and it's too complicated to migrate to using `Context` for now without causing breaking changes.
=> Update to v7.12.1 of JavaScript SDKs

src/main/integrations/electron-breadcrumbs.ts
We noticed an issue where page titles were showing up in breadcrumbs and discovered that the breadcrumbs' `data` properties are references to `RENDERERS` object [here](https://github.com/getsentry/sentry-electron/blob/ef1839a2b2268909ab8f2209dc5f8a5c6fd1fec4/src/main/renderers.ts#L12). Thus, if the page title changes after a breadcrumb is created but before it is sent with an event, [this handler](https://github.com/getsentry/sentry-electron/blob/ef1839a2b2268909ab8f2209dc5f8a5c6fd1fec4/src/main/renderers.ts#L43) will also change the `data` property of the breadcrumb.
This change prevents that by setting the `data` property of the breadcrumb to a clone of the renderer state. Also, this change prevents the breadcrumb integration from modifying the renderer state when writing its `data` …
=> fix: Page titles in breadcrumbs should not change

CHANGELOG.md
https://github.com/getsentry/sentry-electron/tree/3.x is a branch tracking the `3.x` set of releases, it was forked from commit 22c9755c29d9572e2555153add7da011a0080d6a
This PR updates the changelog for 3.0.8, as the fix in https://github.com/getsentry/sentry-electron/pull/551 should be backported to `3.x`. The fix was already cherry-picked onto the `3.x` branch: d9df8135a18903b6747d06699c1e789960f828b0
=> meta: Changelog entry for 3.0.8

.github/workflows/release.yml
See: https://github.com/getsentry/sentry-javascript/pull/4732
Needed to unblock `3.0.8` release as described here: https://github.com/getsentry/sentry-electron/pull/554
Will cherry-pick this onto the `3.x` branch.
=> chore: Add merge target to release action

.github/workflows/build.yml, scripts/e2e-test-versions.js
Closes #559 
Reduce CI e2e tests down to v2 + last 10 versions. Releases are still tested on all versions.
Before:
After:
=> test: Test less Electron versions unless it's a release build

src/main/sdk.ts
Without this, the types do not allow you pass `onFatalError`, etc.
=> `ElectronMainOptions` type should also be a union with `NodeOptions`

README.md, examples/electron-react-boilerplate/package.json, examples/electron-react-boilerplate/src/renderer/index.tsx, examples/electron-vite/index.html, examples/electron-vite/package.json, examples/electron-vite/src/renderer/App.vue, examples/electron-vite/src/renderer/index.mjs, examples/electron-vite/vite.config.renderer.js, src/renderer/sdk.ts, test/e2e/recipe/index.ts
This copies the approach used in [`@sentry/capacitor`](https://github.com/getsentry/sentry-capacitor/blob/6aeb492f540f468f5190c025ebd799fdb7dd3e8e/src/sdk.ts#L20-L23). 
```ts
import * as Sentry from "@sentry/capacitor";
import { init as sentryAngularInit }  from "@sentry/angular";
// Init by passing the sibling SDK's init as the second parameter.
Sentry.init({
dsn: "__DSN__",
}, sentryAngularInit);
```
This involves minimal code changes and is not a breaking change since to the 2nd parameter has a default of the browser init!
I've extended the react and vite example apps to use this approach.
Closes #506
=> feat: Support passing JavaScript framework specific SDK init as second init parameter

src/renderer/ipc.ts
When using `fetch` to communicate with the main process, we include `sentry_key` in the URL so that it does not result in a fetch breadcrumb.
It appears this was left off of the `ping` "command" resulting in a breadcrumb!
=> fix: Include `sentry_key` in ping URL so it does not end up in breadcrumbs

scripts/update-version.js, src/renderer/sdk.ts
Closes #583 
The error reported in the above issue would now read:
```
Argument of type '(if_you_get_a_typescript_error_ensure_sdks_use_version_v7_16_0: import("d:/dev/projects/glint/angular/node_modules/@sentry/browser/types/client").BrowserOptions) => void' is not assignable to parameter of type '(options: import("d:/dev/projects/glint/angular/node_modules/@sentry/electron/node_modules/@sentry/browser/types/client").BrowserOptions) => void'.
Types of parameters 'if_you_get_a_typescript_error_ensure_sdks_use_version_v7_16_0' and 'options' are incompatible.
Type 'import("d:/dev/projects/glint/angular/node_modules/@sentry/electron/node_modules/@sentry/browser/types/client").BrowserOptions' is not assignable to type 'import("d:/dev/projects/glint/angular/node_modules/@sentry/browser/types/cl …
```
=> fix: Change parameter name to give more useful TypeScript error on SDK version mismatch

src/main/integrations/sentry-minidump/index.ts
It was reported that `webContents.forcefullyCrashRenderer()` results in a minidump being generated but `render-process-gone` notifies that the process was `killed`.
We were ignoring all reasons which were not crashes and this resulted in ignoring some minidumps and then sending them on next app start and assuming they came from the main process.
This PR:
- Looks for minidumps for all exit reasons
- Includes the `exit.reason` in tags so customers can filter them
=> fix: Attempt to send minidumps for all `process-gone` reasons

src/main/integrations/sentry-minidump/index.ts, test/e2e/test-apps/native-sentry/main/event.json, test/e2e/test-apps/native-sentry/main/src/main.js
Closes #585
The initial read from the `BufferedWriteStore` is async but writes (to the cached value) were synchronous. This meant that modifications to the scope immediately after calling `init` would overwrite the scope from the previous run.
This PR:
- Wraps the scope updates in `setImmediate` so that the initial read will always win the async race
- Adds a tag to the e2e test to confirm this is working and doesn't get broken again!
=> fix: Ensure any scope updates do not clobber the initial async scope read

src/main/integrations/sentry-minidump/minidump-loader.ts, test/e2e/test-apps/native-sentry/renderer-force-crash/event.json, test/e2e/test-apps/native-sentry/renderer-force-crash/package.json, test/e2e/test-apps/native-sentry/renderer-force-crash/recipe.yml, test/e2e/test-apps/native-sentry/renderer-force-crash/src/index.html, test/e2e/test-apps/native-sentry/renderer-force-crash/src/main.js
Closes #591
On macOS, if you call `webContents.forcefullyCrashRenderer()` the resulting minidump ends up in the `pending` subdirectory and doesn't get copied to completed until the app restarts. This causes it to be classed as a main process crash.
This PR means we now check the `pending` directory for minidumps on macOS and adds a test that ensures minidumps are correctly handled when caused by `webContents.forcefullyCrashRenderer()`.
=> fix: Also check crashpad `pending` directory on macOS when renderer process exits

src/main/integrations/electron-breadcrumbs.ts, test/e2e/recipe/index.ts, test/e2e/recipe/parser.ts, test/e2e/test-apps/other/window-titles/events.ts, test/e2e/test-apps/other/window-titles/package.json, test/e2e/test-apps/other/window-titles/recipe.yml, test/e2e/test-apps/other/window-titles/src/index.html, test/e2e/test-apps/other/window-titles/src/main.js
This PR adds a test to ensure that window titles do not end up in breadcrumbs when this feature is disabled. This is to ensure there is no regression in the behaviour fixed by #551.
The first commit in this PR actually reverses the change in #551 to demonstrate the failing test.
A subsequent commit will reapply #551.
=> test: Add test to ensure window titles don't end up in breadcrumbs when disabled

src/renderer/ipc.ts
While debugging e2e tests I noticed we still capture a breadcrumb for the ping IPC command.
```ts
{
timestamp: 1671415619.64,
category: 'fetch',
data: {
method: 'GET',
url: 'sentry-ipc://sentry-electron.ping/sentry_key',
status_code: 200
},
type: 'http'
}
```
This is because the `@sentry/browser` code that ignores urls with `sentry_key` in them only matches for `POST` requests.
=> fix: Use `POST` for main process ping so it does not result in fetch breadcrumb

.eslintrc.js, package.json, src/common/normalize.ts, src/main/electron-normalize.ts, src/main/integrations/electron-minidump.ts, src/main/integrations/sentry-minidump/minidump-loader.ts, src/main/ipc.ts, src/renderer/sdk.ts, test/e2e/recipe/index.ts, test/e2e/recipe/normalize.ts, test/e2e/server/index.ts, test/e2e/test-apps/other/browser-replay/event-replay.json, test/e2e/test-apps/other/browser-replay/event.json, test/e2e/test-apps/other/browser-replay/package.json, test/e2e/test-apps/other/browser-replay/recipe.yml, test/e2e/test-apps/other/browser-replay/src/index.html, test/e2e/test-apps/other/browser-replay/src/main.js, yarn.lock
Closes #606
This PR:
- Updates the JavaScript SDKs to 7.30.0 for the PRs/changes listed in the above linked issue
- Adds `normalizeUrlsInReplayEnvelope` and calls it with envelopes that are passed through the main process
- Adds a test that checks Replay running in the renderer results in a Replay event
- The test server and test event normalisation required a few changes
This PR initially failed for lint errors in unchanged files. I ended up needing to:
- Update `eslint` version to match the JavaScript monorepo
- Fixed or ignored the new errors
=> feat: Support browser Replay in renderers

examples/electron-forge-webpack/recipe.yml, examples/webpack-context-isolation-preload/recipe.yml, examples/webpack-context-isolation/recipe.yml, test/e2e/recipe/eval.ts, test/e2e/test-apps/other/error-iframe/recipe.yml
For release builds we test all supported Electron versions. 
It [appears](https://github.com/getsentry/sentry-electron/actions/runs/3892651247/jobs/6644902509) that tests involving sandboxed renderers no longer pass on `ubuntu-latest` for older, unsupported versions of Electron.
This PR skips those failing tests.
=> test: Don't run sandbox tests on Linux for Electron < 13

test/e2e/context.ts, test/e2e/index.test.ts
Many older versions of Electron no longer work correctly on `ubuntu-latest` failing with dbus errors and GPU crashes.
Disabling sandbox on Linux gets the tests passing without any obvious risk.
=> test: Disable sandbox for Linux e2e tests

src/renderer/index.ts, test/e2e/test-apps/other/browser-replay/package.json, test/e2e/test-apps/other/browser-replay/src/index.html
While writing the docs I realised Replay should be re-exported for simpler consumption...
=> fix: Replay should be re-exported

src/main/sessions.ts, test/e2e/recipe/index.ts, test/e2e/server/index.ts, test/e2e/test-apps/other/exit-timeout/package.json, test/e2e/test-apps/other/exit-timeout/recipe.yml, test/e2e/test-apps/other/exit-timeout/src/main.js
Closes #643
- Adds a test server route that holds the connection open for 10 seconds
- Adds an e2e test that exits with app expected to be closed within test timeout
- Add 2 second timeout to session flush
=> fix: Add 2 second timeout to session flushing

package.json, src/common/normalize.ts, src/renderer/sdk.ts, test/unit/stack-parse.test.ts, yarn.lock
Replaces #641 because some manual changes were required.
Includes changes due to the addition of `abs_path` to stack trace frames.
=> feat: Update Sentry SDKs to v7.38.0

.github/workflows/build.yml, .github/workflows/new-electron-versions-pr.yml, .github/workflows/new-sdk-versions-pr.yml
As per [the JavaScript monorep](https://github.com/getsentry/sentry-javascript/pull/7763), the Volta cli action is unreliable and `setup-node` now supports using the volta version in package.json.
=> ci: Use `setup-node` rather than `volta`

package.json, src/main/integrations/electron-minidump.ts, src/renderer/sdk.ts, test/unit/stack-parse.test.ts, yarn.lock
This required some manual changes due to `makeDsn` now returning undefined for invalid DSN
=> feat: Update to v7.55.0 of Sentry JavaScript SDKs

package.json, src/main/electron-normalize.ts, src/main/ipc.ts, yarn.lock
Electron v25 introduced `protocol.handle` and [deprecated `protocol.registerStringProtocol`](https://www.electronjs.org/docs/latest/breaking-changes#deprecated-protocolregisterinterceptbufferstringstreamfilehttpprotocol).
=> feat: Use `protocol.handle` on Electron >= v25

src/main/integrations/net-breadcrumbs.ts, test/unit/net.test.ts
=> feat: Tracing without performance

src/main/integrations/sentry-minidump/minidump-loader.ts
It looks like we're getting occasional zero size (or sub 1kB) minidumps that are clearly not valid and these should probably not be sent to Sentry.
=> fix: Don't send minidumps that are likely invalid

test/e2e/test-apps/sessions/abnormal-exit-electron-uploader/src/main.js, test/e2e/test-apps/sessions/abnormal-exit/src/main.js
Looking at the test flakes, they don't occur on my local machine and it looks like in CI the initial `ok` session is not sent from the first instance before it closes. 
This PR extends the app runtime because the Windows VMs are super slow...
=> fix: Flakey session e2e test on Windows

.github/workflows/build.yml
This copies the Ci workflow of the Sentry JavaScript repository. 
It adds a final job that relies on all the other jobs and this can be set as a merge blocker in the GitHub Actions configuration.
=> CI: Add CI job which can be used to block merging

src/common/ipc.ts, src/main/electron-normalize.ts, src/main/ipc.ts, src/preload/index.ts, src/preload/legacy.ts, src/renderer/ipc.ts, test/e2e/test-apps/other/custom-renderer-name-protocol/event.json, test/e2e/test-apps/other/custom-renderer-name-protocol/package.json, test/e2e/test-apps/other/custom-renderer-name-protocol/recipe.yml, test/e2e/test-apps/other/custom-renderer-name-protocol/src/index.html, test/e2e/test-apps/other/custom-renderer-name-protocol/src/main.js
The Electron SDK supports two ways for the renderers to send envelopes and scope to the main process.
- Electron IPC - Preferred but requires a preload script which we attempt to inject automatically but this fails when bundling the main process code
- Custom protocol + fetch - No setup required but Electron does not give us a way to determine which renderer the event came from (https://github.com/electron/electron/issues/31718)
This has meant custom protocol has not supported all the same context as Electron IPC because we're missing the reference to the `webContents`.
This is a problem for renderer ANR detection. We should be able to use the Electron [debugger](https://www.electronjs.org/docs/latest/api/debugger#debuggerattachprotocolversion) API to capture stack traces but once a …
=> feat: Identify `webContents` of renderers via custom protocol 

src/main/sdk.ts
Closes #776
This can still result in a brief flash of the child process in the Dock
=> fix: Hide ANR child process from dock

package.json, src/main/anr.ts, src/main/integrations/net-breadcrumbs.ts, src/main/sdk.ts, src/main/sessions.ts, src/renderer/sdk.ts, test/e2e/test-apps/anr/anr-main/session.json, test/e2e/test-apps/anr/anr-main/src/main.js, test/e2e/test-apps/anr/anr-renderer/session.json, test/e2e/test-apps/anr/anr-renderer/src/main.js, yarn.lock
This PR:
- Updates to the latest js SDKs which had breaking changes around the `watchdogTimer`
- Removes the `lru_map` dependency as there is now an alternative in `@sentry/utils`
- Adds ANR session support for renderer ANR
- Adds tests for both main and renderer ANR sessions
Closes #774 
When adding the tests I found a bug where the ANR child process was picking up the session persistence file and sending it as a previously abnormal session but this file was created by the main process!
=> feat: Update JavaScript SDKs to 7.76.0

src/main/anr.ts, src/main/ipc.ts, test/e2e/test-apps/javascript/renderer-error-protocol/src/main.js
Closes #661
This fix patches the Electron `registerSchemesAsPrivileged` function so that subsequent calls by user code don't overwrite the Sentry scheme.
Unfortunately this Electron API only respects the last schemes passed before app ready and doesn't warn if called multiple times.
=> fix: Patch `registerSchemesAsPrivileged` so sentry scheme isn't overwritten

test/e2e/test-apps/anr/anr-main/recipe.yml, test/e2e/test-apps/anr/anr-renderer/recipe.yml
When trying to publish a release, some ANR tests are failing on very old versions of Electron. It unnecessary to test all these really old versions!
=> test: Only test ANR on newer versions of Electron

scripts/e2e-test-versions.js
For PRs, tested versions are reduced to:
- macOS - Last 3 versions + min supported version 
- Win/Linux - Last 7 versions + min supported version 
This takes us from 33 tested version/platform combinations down to 20.
Release builds still result in all version/platform combinations being tested since there are still a lot of additions and variations in Electron APIs across all these historic versions.
=> test: Test less old Electron versions

src/common/normalize.ts, src/main/integrations/index.ts, src/main/integrations/renderer-profiling.ts, src/main/ipc.ts, src/main/sdk.ts, test/e2e/recipe/index.ts, test/e2e/recipe/normalize.ts, test/e2e/server/index.ts, test/e2e/test-apps/other/browser-profiling/event.json, test/e2e/test-apps/other/browser-profiling/package.json, test/e2e/test-apps/other/browser-profiling/recipe.yml, test/e2e/test-apps/other/browser-profiling/src/index.html, test/e2e/test-apps/other/browser-profiling/src/main.js
Closes #792
Adds a new `RendererProfiling` integration:
- Requires Electron >= v15 (For Chrome 94)
- Enabled via the new `enableRendererProfiling` option
- It adds `'Document-Policy': 'js-profiling'` headers to all renderer requests
- Caches profile envelope items as they arrive in the main process from renderers
- Hooks `beforeEnvelope` to re-add the profiles to the correct envelopes
This PR also adds a test to ensure a profile is sent with the transaction.
From a users perspective, to enable profiling in the renderers, you'll need to pass `enableRendererProfiling: true` in the main process:
```ts
const { init } = require('@sentry/electron/main');
init({
dsn: '__DSN__',
enableRendererProfiling: true,
});
```
Then in the renderer follow the regular browser profiling instructions:
```ts …
```
=> feat: Browser profiling

src/integrations.ts, src/main/integrations/additional-context.ts, src/main/integrations/browser-window-session.ts, src/main/integrations/child-process.ts, src/main/integrations/electron-breadcrumbs.ts, src/main/integrations/electron-minidump.ts, src/main/integrations/main-context.ts, src/main/integrations/main-process-session.ts, src/main/integrations/net-breadcrumbs.ts, src/main/integrations/onuncaughtexception.ts, src/main/integrations/preload-injection.ts, src/main/integrations/renderer-profiling.ts, src/main/integrations/screenshots.ts, src/main/integrations/sentry-minidump/index.ts, src/renderer/integrations/scope-to-main.ts
Migrates all the integrations to use the new functional style.
=> feat: Migrate to functional integration APIs

test/e2e/test-apps/native-sentry/main/event.json, test/e2e/test-apps/native-sentry/main/src/index.html, test/e2e/test-apps/native-sentry/main/src/main.js
Closes #802
This PR adds some console breadcrumbs to a test to ensure we include scope/breadcrumbs from previous run where the main process crashed.
=> test: Ensure correct scope for main process native crashes

src/main/integrations/anr.ts, test/e2e/test-apps/anr/anr-main/recipe.yml, test/e2e/test-apps/native-electron/renderer/event-no-crashpad.json
Release builds test all supported Electron versions and it looks like the minimum supported Node version for ANR is not v16+, is it in fact v16.17.0+.
This brings the minimum supported Electron version up to v22+ which was released 14 months ago.
=> fix: Change ANR minimum Electron version to v22

package.json, src/main/index.ts, src/main/sdk.ts, src/renderer/index.ts, src/renderer/sdk.ts, test/e2e/test-apps/other/browser-replay/src/index.html, yarn.lock
This simply included adding some new exports and ignoring some new deprecations.
=> feat: Update to v7.98.0 of JavaScript SDKs

package.json, src/index.ts, src/main/index.ts, src/renderer/index.ts, src/renderer/sdk.ts, test/e2e/test-apps/other/browser-profiling/src/index.html, test/e2e/test-apps/other/browser-tracing/src/index.html, test/unit/net.test.ts, yarn.lock
Updates to v7.101.0 of the JavaScript SDKs. There we just a few new deprecations.
=> feat: Update JavaScript SDKs to v7.101.0

CHANGELOG.md
Update changelog for v4.18.0 release
Closes #825
Requires #826 to be merged first
=> meta: Update changelog for v4.18.0 release

src/main/integrations/sentry-minidump/index.ts, test/e2e/recipe/index.ts, test/e2e/recipe/parser.ts, test/e2e/test-apps/native-sentry/renderer-limit/event.json, test/e2e/test-apps/native-sentry/renderer-limit/package.json, test/e2e/test-apps/native-sentry/renderer-limit/recipe.yml, test/e2e/test-apps/native-sentry/renderer-limit/src/index.html, test/e2e/test-apps/native-sentry/renderer-limit/src/main.js
Since the Dedupe integration cannot block sending of duplicate minidumps, there is effectively no limit to the number of duplicate minidumps that can be sent per session. 
This PR add a `maxMinidumpsPerSession` option to the integration that defaults to 10.
Internal doc: https://www.notion.so/sentry/096c7ce2987a4e598ca234c82a222853?v=693bea0c95b54382bb9523ab05711127&p=1a1abe81a8ca4689b831efe8bbbb87d9&pm=s
=> feat: Limit minidumps sent per app session

test/e2e/test-apps/native-sentry/renderer-limit/recipe.yml
Older versions of Electron don't support the event used in the test
=> test: Limit crash limits test to latest Electron versions

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
The CodeQL v1 actions were EoL January 18th, 2023 and v2 are EoL later in 2024.
The other actions were also outdated.
=> fix: Update deprecated actions

src/common/scope.ts, src/renderer/integrations/scope-to-main.ts
Clearing the breadcrumbs for a scope that is currently not notifying of changes causes more scope updates to be triggered.
=> fix: Duplicate renderer breadcrumbs

src/main/sdk.ts, src/main/transports/electron-offline-net.ts, test/unit/offline-transport.test.ts
After migrating over to the offline support supplied by `@sentry/core` we lost the ability to force queue events which was previously requested (#489).
This PR adds a `shouldSend` callback which in combination with the `shouldStore` callback restores the previous features.
=> feat: Add `shouldSend` callback to offline transport

scripts/e2e-test-versions.js
I've tested various versions of v20 but they all exit with `SIGTRAP` on macOS arch64 in CI even though it runs and the tests pass locally.
I've spent far too long trying to fix this so I think the best thing for now is to exclude this version in combination with macOS from CI!
=> fix: Don't test v20 in CI on macOS

scripts/e2e-test-versions.js
I was under the impression that the `CI` environment variable is defined in GHA but that doesn't appear to be the case here.
This script is only called in CI so this env check is not required. I've tested this script locally and it does not return v20 on macOS...
=> fix: Don't require CI environment variable

scripts/e2e-test-versions.js, test/e2e/index.test.ts
The test matrix is calculated in the build step so this version needs skipping in the specific e2e test runner
=> test: Skip e2e tests for macOS v20

CHANGELOG.md, package.json, scripts/check-exports.mjs, src/main/index.ts, src/renderer/index.ts, src/renderer/sdk.ts, yarn.lock
Updates to the stable release!
=> feat: Update JavaScript SDKs to v8.2.1 for stable release

CHANGELOG.md
- feat: Update from [v8.0.0](https://github.com/getsentry/sentry-javascript/releases/tag/8.0.0) to [v8.9.2](https://github.com/getsentry/sentry-javascript/releases/tag/8.9.2) of JavaScript SDKs
- feat: Include trace origin in auto spans
=> meta: changelog for 8.1.0 release

package.json, src/renderer/metrics.ts, src/renderer/sdk.ts, yarn.lock
This also adds `Sentry.metrics.timing()`
=> feat: Update Sentry SDKs to v8.14.0

package.json, scripts/check-types.mjs, src/main/integrations/anr.ts
Closes #957
I couldn't get a test to reproduce the above linked issue within this repository so I resorted to regex'ing all the output type defs for sub-module imports.
=> fix: No sub-module imports in type definitions

src/main/sdk.ts
While debugging another issue I found that the `contextLinesIntegration` could not find files because their paths had already been normalised to `app://` base path.
This PR simply ensures that path normalisation occurs last.
=> fix: `contextLinesIntegration` should come before path normalization

package.json, src/main/index.ts, src/renderer/index.ts, src/renderer/sdk.ts, src/utility/index.ts, yarn.lock
Deals with all the deprecations. 
When it comes to the `childProcessIntegration`, the Electron main process retains its own custom integration of this name since this already incorporates the same features as the Node integration with the same name.
=> feat: Update JavaScript SDKs to v8.40.0

package.json, src/main/index.ts, src/main/sdk.ts, src/renderer/index.ts, src/renderer/sdk.ts, src/utility/index.ts, yarn.lock
Updates SDKs to v8.43. 
- Exports the new `disableAnrDetectionForCallback` which closes #1016
- Closes #1029
=> feat: Update JavaScript SDKs to v8.45.0

src/renderer/sdk.ts
- Closes #1030
In the Electron SDK, most of Sentry configuration occurs on the Electron main process because that is where all envelopes are sent from.
We don't support or test setting `dsn`, `environment` and `release` from renderer processes so this should be more clear from the types.
=> fix: Deprecate renderer init options which should only be used in main process

.github/workflows/build.yml, package.json, src/renderer/sdk.ts, test/e2e/test-apps/anr/anr-main/event.json, test/e2e/test-apps/anr/anr-main/recipe.yml, test/e2e/test-apps/anr/anr-main/src/main.js, yarn.lock
Updates JavaScript SDKs to v8.48.0.
The Node SDK has a fix for ANR debug IDs so this PR also includes test changes to confirm this.
- Closes #1011
=> feat: Update JavaScript SDKs to v8.48.0

src/main/integrations/sentry-minidump/index.ts, src/main/integrations/sentry-minidump/minidump-loader.ts, test/e2e/test-apps/native-sentry/unknown/event.json, test/e2e/test-apps/native-sentry/unknown/package.json, test/e2e/test-apps/native-sentry/unknown/recipe.yml, test/e2e/test-apps/native-sentry/unknown/src/index.html, test/e2e/test-apps/native-sentry/unknown/src/main.js, test/unit/minidump-loader.test.ts
- Closes #1047
As described in the above issue:
> Currently we read minidumps from the crashpad directory when we are notified by Electron that a renderer or child process has crashed. We assume that all the minidumps we find correspond the the Electron event. All minidumps we read at startup are assumed to be main process crashes because they cause the process to exit immediately.
>
>Although these assumptions are usually correct, I've personally seen events recorded incorrectly and so have other users (https://github.com/getsentry/sentry-electron/issues/1045).
Rather than fully parse the minidumps as described in the above issue (ie. header + enumerate the streams), we just search for the `process_type` key in the minidump file and pick out the string that follows. This simplified …
=> feat: Determine Electron process from minidump metadata

src/main/transports/offline-store.ts
- Closes #1051
I don't know exactly what caused this issue. I suspect it could be due to an invalid read of the data store.
=> fix: Guard against invalid queue entries

.github/workflows/build.yml, test/e2e/context.ts, test/unit/getPath-test-app/package.json
In a recent PR I had to pin to `ubuntu-22.04` because latest didn't support Electrons sandbox in it's default configuration.
This PR disables the sandbox for the Linux tests and reverts to `ubuntu-latest`. This means we do not test sandbox functionality on Linux but we test other platforms and Electron has extensive tests to cover sandbox behaviour.
=> test: Back to testing on `ubuntu-latest`

test/e2e/test-apps/native-sentry/child-exec/event.json, test/e2e/test-apps/native-sentry/child-exec/package.json, test/e2e/test-apps/native-sentry/child-exec/recipe.yml, test/e2e/test-apps/native-sentry/child-exec/src/index.html, test/e2e/test-apps/native-sentry/child-exec/src/main.js, test/e2e/test-apps/native-sentry/child-fork/event.json, test/e2e/test-apps/native-sentry/child-fork/package.json, test/e2e/test-apps/native-sentry/child-fork/recipe.yml, test/e2e/test-apps/native-sentry/child-fork/src/child.js, test/e2e/test-apps/native-sentry/child-fork/src/index.html, test/e2e/test-apps/native-sentry/child-fork/src/main.js, test/e2e/test-apps/native-sentry/utility/event.json, test/e2e/test-apps/native-sentry/utility/package.json, test/e2e/test-apps/native-sentry/utility/recipe.yml, test/e2e/test-apps/native-sentry/utility/src/child.js, test/e2e/test-apps/native-sentry/utility/src/index.html, test/e2e/test-apps/native-sentry/utility/src/main.js
This PR adds tests for:
- Electron utility process crash
- `child_process.fork` Node process crash
- `child_process.exec` executable crash
Not all platforms can capture child process crashes:
|                    | `event.process`|macOS | Windows | Linux | 
|--------------------|-------|---------|-------|---|
| Electron `utilityProcess`|`utility`|✅|✅|✅ <sup>1</sup>|
| `child_process.fork` | `node`|✅     | ✅       | ❌     |  
| `child_process.exec` | `unknown`|✅     | ❌       | ❌     |  
- <sup>1</sup> Not working with v29.4.6. Possibly an Electron bug that won't get fixed because v29 is already EOL.
=> test: More child process types

src/main/sdk.ts, test/e2e/test-apps/other/no-pii/events.ts, test/e2e/test-apps/other/no-pii/package.json, test/e2e/test-apps/other/no-pii/recipe.yml, test/e2e/test-apps/other/no-pii/src/index.html, test/e2e/test-apps/other/no-pii/src/main.js
This PR:
- Ensures that we only add the ip address if `sendDefaultPii: true`
- Adds a test to ensure the IP address is not added by default
=> fix: Only set `ip.address: '{{auto}}'` when `sendDefaultPii: true`

src/main/anr.ts, src/renderer/anr.ts
- Closes #1035
This PR changes renderer ANR detection to use the Electron `blur`/`focus` events rather than the browser `visibilitychange` events to disable/enable ANR. When the page loses focus, execution can potentially be suspended and the visibilitychange cannot be propigated to main process quickly enough. I also hooked up the power monitor events to disable ANR too.
=> fix: Renderer ANR detection

src/main/integrations/normalize-paths.ts, src/main/normalize.ts, test/e2e/recipe/index.ts, test/e2e/test-apps/other/node-profiling/event.json, test/e2e/test-apps/other/node-profiling/package.json, test/e2e/test-apps/other/node-profiling/recipe.yml, test/e2e/test-apps/other/node-profiling/src/index.html, test/e2e/test-apps/other/node-profiling/src/main.js
- Closes #1052
This PR:
- Ensures that paths in the profile are normalised to the app root
- Adds a test to ensure `@sentry/profiling-node` works with v6.0.0 of the Electron SDK
=> feat: Support `@sentry/profiling-node`

src/main/electron-normalize.ts, src/main/integrations/preload-injection.ts
- Closes #1096
This removes the deprecation warning when using Electron v35
=> feat: Use `registerPreloadScript` in Electron >= v35

src/main/index.ts, src/main/integrations/gpu-context.ts, src/main/sdk.ts, test/e2e/recipe/normalize.ts, test/e2e/test-apps/native-sentry/gpu/event.json, test/e2e/test-apps/native-sentry/gpu/src/main.js
- Closes #1091
If you want full GPU information to be included, you should add the integration with `infoLevel: 'complete'`:
```ts
import * as Sentry from '@sentry/electron/main';
Sentry.init({
dsn: '__DSN__',
integrations: [gpuContextIntegration({ infoLevel: 'complete' })],
});
```
=> feat: Add `gpuContextIntegration`

src/main/integrations/sentry-minidump/index.ts, src/main/integrations/sentry-minidump/minidump-loader.ts, src/main/integrations/sentry-minidump/minidump-parser.ts, test/e2e/test-apps/native-sentry/renderer/event.json, test/unit/minidump-loader.test.ts
- Closes #1094 
Previously we pulled the `process_type` value from the minidump via some crude parsing.
This PR adds a full parser to pull annotations from the crashpad stream in the minidumps and includes them in the event `electron` context but prepends `crashpad.` to all the keys. This allows users to use this context in `beforeSend` filters and in other sampling decisions.
Electron includes additional v8 context in the crashpad metadata (like `electron.v8-oom.detail` which gives details about the OOM reason):
https://github.com/electron/electron/blob/d987bee0073310c0bf114dd5e5c9db5e9c68ee59/shell/common/node_bindings.cc#L193
The parser code was mostly aided by the `rust-minidump` crate which has great documentation. I've credited it fully in the source because it would have been a lot …
=> feat: Parse crashpad metadata from minidumps and include in `electron` context

src/main/integrations/sentry-minidump/index.ts
=> fix: Electron `app.getPath('crashDumps')` API can throw

src/common/ipc.ts, src/main/ipc.ts, src/preload/index.ts, src/renderer/ipc.ts
While working on #1117 I found that we have a `sentEvent` IPC method that is no longer used!
=> chore: Remove unused IPC method

package.json, scripts/check-exports.mjs, src/main/index.ts, src/main/integrations/electron-minidump.ts, src/main/integrations/gpu-context.ts, src/main/integrations/sentry-minidump/index.ts, src/main/ipc.ts, src/main/transports/electron-net.ts, src/renderer/sdk.ts, src/renderer/stack-parse.ts, src/utility/index.ts, test/e2e/server/index.ts, yarn.lock
This PR:
- Updates to the latest JavaScript SDKs
- Replaces usages of deprecated `SentryError` with `Error`. These usages were only for errors that should never occur.
- Removes usages of deprecated `dropUndefinedKeys`
=> feat: Update JavaScript SDKs to v9.10.1

.github/workflows/build.yml
Ubuntu 20.04 has been deprecated in GHA
=> CI: Remove Ubuntu 20.04 usage in CI

src/main/integrations/gpu-context.ts, test/e2e/recipe/normalize.ts, test/e2e/test-apps/native-sentry/gpu/event.json
I added `device_id` to the GPU context but when I went to PR to the develop docs, I noticed this should just be `id`!
=> fix: GPU context should use `id` rather than `device_id`

src/main/integrations/additional-context.ts, test/e2e/recipe/normalize.ts, test/e2e/test-apps/other/device-context/event.json, test/e2e/test-apps/other/device-context/package.json, test/e2e/test-apps/other/device-context/recipe.yml, test/e2e/test-apps/other/device-context/src/main.js
- Closes #1112 
This PR adds to the `additionalContextIntegration` so you can optionally include the manufacturer and model in the device context:
```ts
import * as Sentry from '@sentry/electron/main';
Sentry.init({
dsn: '__DSN__',
integrations: [Sentry.additionalContextIntegration({ deviceModelManufacturer: true })]
});
```
It's worth noting that testing this on my Windows laptop, pulling this data via powershell takes around 400ms. This is a one-off cost as the result is cached. This data is captured asynchronously but it will delay sending of the first event.
=> feat: Optionally capture manufacturer and model device context

README.md
I just noticed that the minimum supported Electron version was not updated at the last major!
=> docs: Fix minimum supported version in readme

package.json, src/main/index.ts, src/main/transports/electron-offline-net.ts, src/renderer/sdk.ts, src/utility/index.ts, yarn.lock
The `shouldSend` callback handling has been removed from the Electron SDK as this feature is now included in the Core offline support.
=> feat: Update JavaScript SDKs to v9.13.0

package.json, src/main/integrations/electron-context.ts, src/main/sdk.ts, src/renderer/index.ts, src/renderer/sdk.ts, src/utility/sdk.ts, yarn.lock
This also uses the new `includeServerName` option so we no longer need to strip the `server_name` from events or logs.
=> feat: Update JavaScript SDKs to v9.25.0

test/e2e/test-apps/other/event-listener/test.ts
This PR disables a single test on Linux which appears to be the biggest culprit for test failures. 
This test was originally added to ensure we don't retain (and leak) event listeners for Electron Windows but it's not a requirement for this to be tested on every platform.
=> test: Fix e2e test flakes

test/e2e/test-apps/native-sentry/main-update/test.ts
This test is flakey on Ubuntu in CI
=> test: Disable update test that flakes on Linux

package.json, src/main/merge.ts, test/e2e/test-apps/other/circular-merge/package.json, test/e2e/test-apps/other/circular-merge/src/main.js, test/e2e/test-apps/other/circular-merge/test.ts, yarn.lock
=> fix: Don't use `deepmerge` to merge events to remove circular ref. issues

CHANGELOG.md, src/preload/index.ts, src/renderer/ipc.ts, test/e2e/test-apps/other/preload-injection/main.js, test/e2e/test-apps/other/preload-injection/package.json, test/e2e/test-apps/other/preload-injection/renderer.js, test/e2e/test-apps/other/preload-injection/test.ts, test/e2e/test-apps/other/preload-injection/webpack.config.js
- Closes #1242
This was a classic example of why you shouldn't try get a quick fix out (#1243) before fixing the tests that caused the bug to be missed 🫠
After ensuring we had a test that covers this specific scenario, I found a couple of other issues.
Rather than add new test, I repurposed an existing bundler test which has become redundant since we added so many bundling examples.
=> fix: Preload `contextIsolation` issues
